# Generated by Django 5.0.7 on 2024-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='нет2', max_length=30, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
    ]
